Add veryFineDustSensor Capability
pySmartThings/pysmartthings pull request #76
Opened 2023-07-29 15:21 UTC by LeeHanYeong

https://developer.smartthings.com/docs/devices/capabilities/capabilities-reference/#veryFineDustSensor
It indicates the level of very-fine dust (PM1.0) in air monitors, air purifiers, and air conditioners.

## Description:

<details of changes goes here>

**Related issue (if applicable):** fixes #<pysmartthings issue number goes here>

## Checklist:

- [x] The code change is tested and works locally.
- [x] Local tests pass.
- [x] There is no commented out code in this PR.
- [x] Tests have been added/updated and code coverage percentage does not drop. No exclusions in `.coveragerc` allowed
- [x] `README.MD` updated (if necessary)

2023-09-10 22:12 UTC, baawiki commented
Hi @LeeHanYeong! 

I came here for the same thing :)

I've sent GH-78 which adds `veryFineDustLevel` as an attribute to the single `dustSensor`, that seems to be consistent with how the existing `dustLevel` and `fineDustLevel` attributes are implemented.

Hopefully at least one of our PRs will get accepted :)

2023-09-11 07:37 UTC, baawiki commented
@LeeHanYeong just following the earlier comment, I've dropped my pull request as we don't need two for the same feature.

The only thing I see missing from yours is an update on the `CAPABILITIES_TO_ATTRIBUTES` map.  I *think* you need to add:
```
"veryFineDustSensor": ["veryFineDustLevel"],
```
somewhere around line 140.

HTH!

2023-09-18 18:51 UTC, andrewsayre requested changes
Thanks for the contribution @LeeHanYeong! As @baawiki mentioned, there's one additional update needed in the `CAPABILITIES_TO_ATTRIBUTES` map. Once edited there, this is good to go!

2023-09-19 03:17 UTC, LeeHanYeong commented
@baawiki Thanks for the help with the missing code.
@andrewsayre I added the above code to my PR.

2025-02-12 22:20 UTC, joostlek commented
This has been added! If you still happen to have such device and are able to get fixtures, that would be amazing!

2025-02-12 22:20 UTC, closed without merging